### ISSUE TITLE
Filter for ressurser som har blitt endret de siste x dagene

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-search-service#147]
Filteret `lastXDays` baserer seg på `metadata.firstHarvested`og gir ressursene som har blitt publisert til fdk de siste x dagene, rss-atom-feed har behov for et lignende filter, men basert på `metdata.modified`

Se feks til implementasjonen av filteret til lastXDays: https://github.com/Informasjonsforvaltning/fdk-search-service/blob/main/src/main/kotlin/no/digdir/fdk/searchservice/service/SearchService.kt#L303-L311

**Comment by jeffreiffers** [comment]
@terjesyl modified date ligger lagret under metadata.changed (som er en liste). Dette er legacy og kommer fra rdf-parser. Vi kan gjøre to ting:

1. Endre RdfParser changed (list) -> modified (date string value)
2. Bruke changed as is. Litt usikker hvordan vi skal forholde oss til en liste.

**Comment by NilsOveTen** [comment]
> @terjesyl modified date ligger lagret under metadata.changed (som er en liste). Dette er legacy og kommer fra rdf-parser. Vi kan gjøre to ting:
> 
>     1. Endre RdfParser changed (list) -> modified (date string value)
> 
>     2. Bruke changed as is. Litt usikker hvordan vi skal forholde oss til en liste.

Eneste bruken jeg kan finne av `changed` er noen utdaterte tester i fdk-portal, jeg stemmer for at vi endrer parser-koden. Om vi venter blir dette sannsynligvis mer komplisert å ta tak i...

**Comment by terjesyl** [comment]
Høres bra ut, at vi endrer fdk-rdf-parser.

**Comment by terjesyl** [comment]
Har laget issue: https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/283
