### ISSUE TITLE
motta søk på datasett indeks

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/fdk-search-service#21]
indesks : dataset-search
datasetmodel: https://github.com/Informasjonsforvaltning/fdk-rdf-parser/blob/main/src/fdk_rdf_parser/classes/dataset.py 

(start med tittle, beskrivelse, og at det kan gjøres søk på det)

endepunktet: `/search`, `POST`, body `{q: søkeord:string}`

**Comment by NilsOveTen** [comment]
Implementer støtte for alle feltene som støttes i dagens løsning, ref `index_fulltext_fields` her: https://github.com/Informasjonsforvaltning/fdk-fulltext-search/blob/main/src/fdk_fulltext_search/search/fields.py

så for datasett er det disse feltene som er relevante:
- [ ] title.*
- [ ] objective.*
- [ ] keyword.*
- [ ] theme.title.*
- [ ] losTheme.name.*
- [ ] description.*
- [ ] publisher.name
- [ ] publisher.prefLabel
- [ ] accessRights.prefLabel.*
- [ ] accessRights.code
- [ ] subject.prefLabel.*
- [ ] subject.altLabel.*
- [ ] subject.definition.*
- [ ] distribution.title.*

(de som slutter på `.*` er språkfelt og vi skal støtte bokmål, nynorsk og engelsk for disse, feks så vil `title.*` bli `title.nb`, `title.nn` og `title.en`)
