### ISSUE TITLE
Søk på datatjenester indeks

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/fdk-search-service#30]
- [x] "title.*^3",
- [x] "description.*",
- [x] "publisher.name^3",
- [x] "publisher.prefLabel^3",

**Comment by hegeaal** [comment]
Refakturer. 

- [ ] Må  flytte funksjonalitet i dataserviceSearchService til den nye generelle searchService. 
- [ ] Utvide searchType ENUM med dataservice. Opprette filter på ENUM/ta i bruk searchType filter for dataService. 
- [ ] Mapper av dataservice til generelt søkeobjekt.

**Comment by hegeaal** [comment]
**Mapping**

id -> id
title -> title
description -> description
publisher -> organization
