### ISSUE TITLE
Legge til støtte for filter som kreves for tilgangsfilterboks for datasett

### ISSUE THREAD

**Issue by hegeaal** [Informasjonsforvaltning/fdk-search-service#35]
- [x] accessRights felt, enum [Ukjent, PUBLIC, RESTRICTED, NON_PUBLIC] -> kan ta inn en string. JSON-path: accessRights.code
- [x] OpenData felt, boolean. json-path: isOpenData.

Json-path = feltverdi til elastic. termsBuilder.field("json-path")

**Comment by jeffreiffers** [comment]
Denne henger tett sammen med https://github.com/Informasjonsforvaltning/fdk-search-service/issues/36. Kan dette konsolideres?
