### ISSUE TITLE
Søk på informasjonsmodeller

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-search-service#37]
indeks: `fdk-information-model-search`
endepunkt: `/informationmodels`
metode: POST
body: `{"q":"søkeverdi"}`

felter:
- title.nb
- title.nn
- title.en
- keyword -> liste objekter med språkfelt
- theme.title.nb
- theme.title.nn
- theme.title.en
- losTheme.name.nb
- losTheme.name.nn
- losTheme.name.en
- description.nb
- description.nn
- description.en
- publisher.name
- publisher.prefLabel

**Comment by hegeaal** [comment]
Refakturer. 

- [ ] Må  flytte funksjonalitet i informationModelSearchService til den nye generelle searchService. 
- [ ] Utvide searchType ENUM med  informationModel. Opprette filter på ENUM/ta i bruk searchType filter for  informationModel. 
- [ ] Mapper av  informationModel til generelt søkeobjekt.

**Comment by hegeaal** [comment]
**Mapping**

id -> id
title -> title
description -> description
publisher -> organization
