### ISSUE TITLE
fdk-search-service skal motta kafka-meldinger om ferdig parse

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-search-service#5]
- [x] datasett
- [x] begrep
- [x] datatjenester
- [x] informasjonsmodeller
- [x] hendelser
- [x] tjenester

**Comment by KurtStian** [comment]
Inspirasjon i fra MQA DCAT validator.

**Comment by pooriamehregan** [comment]
@jeffreiffers har løst dette i egen pr
