### ISSUE TITLE
Søk på tjenester

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/fdk-search-service#50]
indeks: `fdk-services-search`
endepunkt: `/services`
metode: POST
body: `{"q":"søkeverdi"}`

felter:
- title.nb
- title.nn
- title.en
- description.nb
- description.nn
- description.en
- ~~hasCompetentAuthority.name~~
- ~~hasCompetentAuthority.prefLabel~~

**Comment by hegeaal** [comment]
Refakturer. 

- [ ] Må  flytte funksjonalitet i ServiceSearchService til den nye generelle searchService. 
- [ ] Utvide searchType ENUM med  Service. Opprette filter på ENUM/ta i bruk searchType filter for Service. 
- [ ] Mapper av Service til generelt søkeobjekt.

**Comment by hegeaal** [comment]
Mapping

id -> id
title -> title
description -> description
hasCompetentAuthority -> organization
