### ISSUE TITLE
Søk på hendelser

### ISSUE THREAD

**Issue by hegeaal** [Informasjonsforvaltning/fdk-search-service#52]
indeks: fdk-services-events
endepunkt: /events
metode: POST
body: {"q":"søkeverdi"}

felter:

title.nb
title.nn
title.en
description.nb
description.nn
description.en
~~hasCompetentAuthority.name~~
~~hasCompetentAuthority.prefLabel~~

**Comment by pooriamehregan** [comment]
`hasCompetentAuthority` finnes ikke i `fdk-rdf-parser`. Dette er et felt som ikke finnes i spesifikasjonen og er fjernet fra parseren.

**Comment by hegeaal** [comment]
Refakturer. 

- [ ] Må  flytte funksjonalitet i EventSearchService til den nye generelle searchService. 
- [ ] Utvide searchType ENUM med  Event. Opprette filter på ENUM/ta i bruk searchType filter for Event. 
- [ ] Mapper av Event til generelt søkeobjekt.

**Comment by hegeaal** [comment]
**Mapping**

id -> id
title -> title
description -> description
