### ISSUE TITLE
Generaliser alle ressurser til samme datamodell

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-search-service#58]
- id: Alle (fdkId)
- uri: Alle (identifier)
- title: Alle (prefLabel)
- description: Alle (definition)
- harvest: Alle
- catalog: Alle (collection)
- organization: Alle (publisher, competentAuth)
- keyword: Datasett og informasjonsmodeller
- dataTheme: Datasett og informasjonsmodeller
- losTheme: Datasett og informasjonsmodeller
- fdkFormat: Datasett og datatjenester
- isOpenData: Datasett
- accessRights: Datasett
- provenance: Datasett
- spatial: Datasett
- searchType: Enum (concept, dataset)

I tillegg kommer det en del diverse relasjoner, som feks relation, requires, groupedBy osv
kan vi i stedet holde oss til en liste `relations` som har feltene `uri` og `type`, der uri er uri til ressursen det relateres til og type er relasjonstypen `{"relations": {"uri": "https://concept.uri", "type": "replaces"}}`

**To do:**

- [x] Lag en ny (felles) model som har disse feltene
- [x] Lag en `SearchService `basert på denne modellen og fjern `conceptSearchService`og `datasetSearchService`
- [x] Lag en `SearchRepository` og fjern concept og dataset repository
- [x] Lag mapper fra dataset til generisk søkobjekt og mapper fra concept til generisk søkobjekt. Kan legges i en mapper-pakke (kotlin-fil med statiske metoder).
- [x] Fikse testene

**Comment by terjesyl** [comment]
Vi tar ut
- objective (fra dcatapno)
- distribution (tittel på Distribusjon til datasett)
- subject (brukes på datasett og begrep)

`objective` er ikke i bruk lenger, ingen ressurser i katalogen bruker denne egenskapen.
Vi vurderer det til at distribution og subject på datasett ikke er relevant i dagens søk, og gjøre søket potensielt mer forvirrende. Kan reintroduseres ved et avansert søk senere.
Fagområde (begrep:subject) kan støttes ved filter.

**Comment by terjesyl** [comment]
En problemstilling knyttet til søk på relasjoner:
Detaljsiden i portal gjør søk for ressursene for å hente informasjon om relasjoner til andre ressurser. Dette søket gjøres for hvert besøk til en detaljvisning.

Bør undersøke muligheten for å legge på informasjon om relasjoner under parse-jobben sånn at det er tilgjengelig på dataen som hentes fra resource-service. Da unngår vi alle relasjonssøkene fra detaljvisningene.

Informasjonen kan potensielt legges på i reasoning-service, men det krever en del endringer der.

**Comment by hegeaal** [comment]
**Mapping for begrep**

id -> id
publisher -> organization
definition -> description
prefLabel -> title
subject -> fjernes

**Mapping for dataset**

id -> id
title -> title
description -> description
objective -> fjernes
keyword -> keyword
theme -> euTheme
losTheme -> losTheme
publisher -> organization
accessRights -> accessRights
subject -> fjernes
distribution -> fjernes
isOpenData -> isOpenData
spatial -> spatial
