### ISSUE TITLE
Legg til filter for format

### ISSUE THREAD

**Issue by hegeaal** [Informasjonsforvaltning/fdk-search-service#66]
Feltnavn i filter-body: "fdkFormat"
Verditype i filter-body: string
Feltnavn som det skal filtreres i: "fdkFormatPrefixed.keyword"

**Comment by NilsOveTen** [comment]
fulltext transformerer formater til fdkFormatPrefixed selv: https://github.com/Informasjonsforvaltning/fdk-fulltext-search/blob/8a0a2ebd355b691a63ccf9609c379dd5fd922db2/src/fdk_fulltext_search/ingest/__init__.py#L504-L532

I hvert fall i starten må nok fdk-search-service gjøre det samme.
