### ISSUE TITLE
Konfigurere elastic til å støtte losPaths og orgPaths

### ISSUE THREAD

**Issue by hegeaal** [Informasjonsforvaltning/fdk-search-service#68]
For eksempel: 
De som har` orgPath = "/STAT/972417882"` skal dukke opp i filter "/STAT" og "/STAT/972417882"

De som har `losPath = "trafikk-og-transport/mobilitetstilbud"` skal dukke opp i filter "trafikk-og-transport" og "trafikk-og-transport/mobilitetstilbud". 

fra fulltext har disse feltene konfigurert en egen analyzer for at feltene skal fungere som tenkt. Se feks konfigurering av datasett i fulltext:

https://github.com/Informasjonsforvaltning/fdk-fulltext-search/blob/main/elasticsearch/create_datasets_index.json#L1266
https://github.com/Informasjonsforvaltning/fdk-fulltext-search/blob/main/elasticsearch/create_datasets_index.json#L1459
https://github.com/Informasjonsforvaltning/fdk-fulltext-search/blob/main/elasticsearch/create_datasets_index.json#L2120-L2145

**Comment by NilsOveTen** [comment]
Vi kan feks registrere samme analyzer via `@Setting(settingPath = "/elastic/settings.json")`, og så ta i bruk korrekt analyzer via `@Field(type = FieldType.Text, analyzer = "path_analyzer")`
