### ISSUE TITLE
Legg til støtte for filtrering basert på relasjoner

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-search-service#69]
Det må være mulig å søke etter alle ressurser som relaterer til en gitt ressurs-uri.

Vil legge til feltet relations i searchObject. Må mappe for hver ressurstype til dette formatet, der uri er uri'en til ressursen den blir relatert til, og type er relasjonstype(enum). 

```
{
      "relations": [
               {
                 "uri": "https://concept.uri", 
                 "type": "replaces"
                }
          ]
}
```

**Comment by hegeaal** [comment]
**Relasjoner i data services (api)**

1. conformsTo
2. servesDataset

**Comment by hegeaal** [comment]
**Relasjon i begrep**

1. associativeRelation
2. closeMatch
3. exactMatch
4. genericRelation
5. isReplacedBy
6. memberOf
7. partitiveRelation
8. replaces
9. seeAlso

**Comment by hegeaal** [comment]
**Relasjon i informasjonsmodell**
1. containsSubjects ? (se nærmere på denne)
2. conformsTo
3. hasPart
4. isPartOf
5. isProfileOf
6. isReplacedBy
7. replaces
8. subjects

**Comment by hegeaal** [comment]
**Relasjon i tjeneste**

1. follows
2. hasLegalResource
3. isGroupedBy
4. isClassifiedBy ? Se nærmere
5. isDescribedAt ? Se nærmere
6. relation
7. requires
8. subject ?

**Comment by hegeaal** [comment]
**Hendelse**

1. mayTrigger
